/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TemaTest;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;

public class App {
    static int postid = 1;
    static int commentid = 1;
    public App() {/* compiled code */}

    public static void main(java.lang.String[] strings) {
        if (strings == null) {
            System.out.println("Hello world!");
            return;
        }

        /* compiled code */
        if(strings[0].equals("-create-user")) {

            if(strings.length < 2)
                System.out.println("{ 'status' : 'error', 'message' : 'Please provide username'}");
            else if(strings.length < 3) {
                System.out.println("{ 'status' : 'error', 'message' : 'Please provide password'}");}
            else {
                String[] username = strings[1].split("'");
                String[] password = strings[2].split("'");
                Users user = new Users(username[1], password[1]);
                try (BufferedReader br = new BufferedReader(new FileReader("users.txt"))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        String[] parts = line.split(",");
                        if(parts[0].equals(user.getUsername())) {
                            System.out.println("{'status': 'error','message':'User already exists'}");
                            return;
                        }
                    }
                } catch (IOException e) {
                }

                try (FileWriter fw = new FileWriter("users.txt", true);
                BufferedWriter bw = new BufferedWriter(fw);
                PrintWriter out = new PrintWriter(bw)) {
                    out.println(user.getUsername() + "," + user.getPassword());
                } catch (IOException e) {
                }
                System.out.println("{'status':'ok','message':'User created successfully'}");
            }
        }

        if(strings[0].equals("-create-post")) {
            int ok = 0;
            if(strings.length <= 2)
                System.out.println("{ 'status' : 'error', 'message' : 'You need to be authenticated'}");
            else {
                String[] username = strings[1].split("'");
                String[] password = strings[2].split("'");
                try (BufferedReader br = new BufferedReader(new FileReader("users.txt"))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        String[] parts = line.split(",");
                        if(parts[0].equals(username[1])) {
                            if(parts[1].equals(password[1]))
                                ok = 1;
                        }
                    }
                } catch (IOException e) {
                }
                if(ok == 0){
                    System.out.println("{ 'status' : 'error', 'message' : 'Login failed'}");
                    return;
                }
            }
            if(ok == 1) {
                if(strings.length < 4)
                    System.out.println("{ 'status' : 'error', 'message' : 'No text provided'}");
                else {
                    String[] text = strings[3].split("'");
                    if(text[1].length() > 300){
                        System.out.println("{ 'status' : 'error', 'message' : 'Post text length exceeded'}");
                        return;
                    }
                    String[] username = strings[1].split("'");
                    LocalDate date = LocalDate.now();
                    DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
                    Post post = new Post(text[1], username[1], postid, date.format(dateFormatter));
                    postid++;
                    try (FileWriter fw = new FileWriter("posts.txt", true);
                    BufferedWriter bw = new BufferedWriter(fw);
                    PrintWriter out = new PrintWriter(bw)) {
                        out.println(post.getId() + "," + post.getUsername() + "," + post.getText()+ "," + post.getDate());
                    } catch (IOException e) {
                    }
                    System.out.println("{'status' : 'ok' , 'message' : 'Post added successfully'}");
                }
            }
        }

        if(strings[0].equals("-delete-post-by-id")) {
            int ok = 0;
            int ok2 = 0;
            if(strings.length <= 2)
                System.out.println("{ 'status' : 'error', 'message' : 'You need to be authenticated'}");
            else {
                String[] username = strings[1].split("'");
                String[] password = strings[2].split("'");
                try (BufferedReader br = new BufferedReader(new FileReader("users.txt"))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        String[] parts = line.split(",");
                        if(parts[0].equals(username[1])) {
                            if(parts[1].equals(password[1]))
                                ok = 1;
                        }
                    }
                } catch (IOException e) {
                }
                if(ok == 0){
                    System.out.println("{ 'status' : 'error', 'message' : 'Login failed'}");
                    return;
                }
            }
            if(ok == 1) {
                if(strings.length < 4)
                    System.out.println("{ 'status' : 'error', 'message' : 'No identifier was provided'}");
                else{
                    String[] username = strings[1].split("'");
                    String[] id = strings[3].split("'");
                    ArrayList<String> vector = new ArrayList<String>();
                    try (BufferedReader br = new BufferedReader(new FileReader("posts.txt"))) {
                        String line;
                        while ((line = br.readLine()) != null) {
                            String[] parts = line.split(",");
                            if(parts[0].equals(id[1])) {
                                ok2 = 1;
                                continue;
                            }
                            vector.add(line);
                        }
                    } catch (IOException e) {
                    }
                    if(ok2 == 0){
                        System.out.println("{ 'status' : 'error', 'message' : 'The identifier was not valid'}");
                        return;
                    } else {
                        try (FileWriter fw = new FileWriter("posts.txt", false);
                             BufferedWriter bw = new BufferedWriter(fw);
                             PrintWriter out = new PrintWriter(bw)) {
                            out.println("");
                        } catch (IOException e) {
                        }
                        for (int i = 0; i < vector.size(); i++) {
                            try (FileWriter fw = new FileWriter("posts.txt", true);
                                 BufferedWriter bw = new BufferedWriter(fw);
                                 PrintWriter out = new PrintWriter(bw)) {
                                out.println(vector.get(i));
                            } catch (IOException e) {
                            }
                        }
                        System.out.println("{'status':'ok','message':'Post deleted successfully'}");
                    }
                }
            }
        }

        if(strings[0].equals("-follow-user-by-username")){
            int ok = 0;
            int ok2 = 0;
            if(strings.length <= 2)
                System.out.println("{ 'status' : 'error', 'message' : 'You need to be authenticated'}");
            else {
                String[] username = strings[1].split("'");
                String[] password = strings[2].split("'");
                try (BufferedReader br = new BufferedReader(new FileReader("users.txt"))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        String[] parts = line.split(",");
                        if(parts[0].equals(username[1])) {
                            if(parts[1].equals(password[1]))
                                ok = 1;
                        }
                    }
                } catch (IOException e) {
                }
                if(ok == 0){
                    System.out.println("{ 'status' : 'error', 'message' : 'Login failed'}");
                    return;
                }
            }
            if(ok == 1) {
                if(strings.length <= 3)
                    System.out.println("{ 'status' : 'error', 'message' : 'No username to follow was provided'}");
                else {
                    String[] usernameToFollow = strings[3].split("'");
                    String[] username = strings[1].split("'");
                    try (BufferedReader br = new BufferedReader(new FileReader("users.txt"))) {
                        String line;
                        while ((line = br.readLine()) != null) {
                            String[] parts = line.split(",");
                            if(parts[0].equals(usernameToFollow[1])) {
                                ok2 = 1;
                                try (BufferedReader br2 = new BufferedReader(new FileReader("followers.txt"))) {
                                    String line2;
                                    while ((line2 = br2.readLine()) != null) {
                                        String[] parts2 = line2.split(",");
                                        if(parts2[0].equals(username[1]) && parts2[1].equals(usernameToFollow[1])) {
                                            System.out.println("{ 'status' : 'error', 'message' : 'The username to follow was not valid'}");
                                            return;
                                        }
                                    }
                                } catch (IOException e) {
                                }

                                try (FileWriter fw = new FileWriter("followers.txt", true);
                                BufferedWriter bw = new BufferedWriter(fw);
                                PrintWriter out = new PrintWriter(bw)) {
                                    out.println(username[1] + "," + usernameToFollow[1]);
                                } catch (IOException e) {
                                }
                                System.out.println("{'status':'ok','message':'Operation executed successfully'}");
                                return;
                            }
                        }
                    } catch (IOException e) {
                    }
                    if(ok2 == 0){
                        System.out.println("{ 'status' : 'error', 'message' : 'The username to follow was not valid'}");
                        return;
                    }
                }
            }
        }

        if(strings[0].equals("-unfollow-user-by-username")) {
            int ok = 0;
            int ok2 = 0;
            if(strings.length <= 2)
                System.out.println("{ 'status' : 'error', 'message' : 'You need to be authenticated'}");
            else {
                String[] username = strings[1].split("'");
                String[] password = strings[2].split("'");
                try (BufferedReader br = new BufferedReader(new FileReader("users.txt"))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        String[] parts = line.split(",");
                        if(parts[0].equals(username[1])) {
                            if(parts[1].equals(password[1]))
                                ok = 1;
                        }
                    }
                } catch (IOException e) {
                }
                if(ok == 0){
                    System.out.println("{ 'status' : 'error', 'message' : 'Login failed'}");
                    return;
                }
            }
            if(ok == 1) {
                if(strings.length <= 3)
                    System.out.println("{ 'status' : 'error', 'message' : 'No username to unfollow was provided'}");
                else {
                    String[] userToUnfollow = strings[3].split("'");
                    String[] username = strings[1].split("'");
                    try (BufferedReader br = new BufferedReader(new FileReader("followers.txt"))) {
                        String line;
                        while ((line = br.readLine()) != null) {
                            String[] parts = line.split(",");
                            if(parts[0].equals(username[1]) && parts[1].equals(userToUnfollow[1])) {
                                ok2 = 1;
                                try (FileWriter fw = new FileWriter("followers.txt", false);
                                BufferedWriter bw = new BufferedWriter(fw);
                                PrintWriter out = new PrintWriter(bw)) {
                                    out.println("");
                                } catch (IOException e) {
                                }
                                System.out.println("{'status':'ok','message':'Operation executed successfully'}");
                                return;
                            }
                        }
                    } catch (IOException e) {
                    }
                    if(ok2 == 0){
                        System.out.println("{ 'status' : 'error', 'message' : 'The username to unfollow was not valid'}");
                        return;
                    }
                }
            }
        }

        if(strings[0].equals("-like-post")) {
            int ok = 0;
            if(strings.length <= 2)
                System.out.println("{ 'status' : 'error', 'message' : 'You need to be authenticated'}");
            else {
                String[] username = strings[1].split("'");
                String[] password = strings[2].split("'");
                try (BufferedReader br = new BufferedReader(new FileReader("users.txt"))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        String[] parts = line.split(",");
                        if(parts[0].equals(username[1])) {
                            if(parts[1].equals(password[1]))
                                ok = 1;
                        }
                    }
                } catch (IOException e) {
                }
                if(ok == 0){
                    System.out.println("{ 'status' : 'error', 'message' : 'Login failed'}");
                    return;
                }
            }
            if(ok == 1){
                if(strings.length <= 3)
                    System.out.println("{ 'status' : 'error', 'message' : 'No post identifier to like was provided'}");
                else {
                    String[] id = strings[3].split("'");
                    String[] username = strings[1].split("'");
                    Post post = new Post("", "", 0, "");
                    post.like(username, id);
                }
            }
        }

        if(strings[0].equals("-unlike-post")) {
            int ok = 0;
            if(strings.length <= 2)
                System.out.println("{ 'status' : 'error', 'message' : 'You need to be authenticated'}");
            else {
                String[] username = strings[1].split("'");
                String[] password = strings[2].split("'");
                try (BufferedReader br = new BufferedReader(new FileReader("users.txt"))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        String[] parts = line.split(",");
                        if(parts[0].equals(username[1])) {
                            if(parts[1].equals(password[1]))
                                ok = 1;
                        }
                    }
                } catch (IOException e) {
                }
                if(ok == 0){
                    System.out.println("{ 'status' : 'error', 'message' : 'Login failed'}");
                    return;
                }
            }
            if(ok == 1){
                if(strings.length <= 3)
                    System.out.println("{ 'status' : 'error', 'message' : 'No post identifier to unlike was provided'}");
                else {
                    String[] id = strings[3].split("'");
                    String[] username = strings[1].split("'");
                    Post post = new Post("", "", 0, "");
                    post.unlike(username, id);
                }
            }
        }

        if(strings[0].equals("-comment-post")) {
            int ok = 0;
            if(strings.length <= 2)
                System.out.println("{ 'status' : 'error', 'message' : 'You need to be authenticated'}");
            else {
                String[] username = strings[1].split("'");
                String[] password = strings[2].split("'");
                try (BufferedReader br = new BufferedReader(new FileReader("users.txt"))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        String[] parts = line.split(",");
                        if(parts[0].equals(username[1])) {
                            if(parts[1].equals(password[1]))
                                ok = 1;
                        }
                    }
                } catch (IOException e) {
                }
                if(ok == 0){
                    System.out.println("{ 'status' : 'error', 'message' : 'Login failed'}");
                    return;
                }
            }
            if(ok == 1) {
                if(strings.length < 5)
                    System.out.println("{ 'status' : 'error', 'message' : 'No text provided'}");
                else {
                    String[] text = strings[4].split("'");
                    if(text[1].length() > 300){
                        System.out.println("{ 'status' : 'error', 'message' : 'Comment text length exceeded'}");
                        return;
                    }
                    String[] username = strings[1].split("'");
                    String[] id = strings[3].split("'");
                    LocalDate date = LocalDate.now();
                    DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
                    Comment comment = new Comment(text[1], username[1], commentid, date.format(dateFormatter));
                    commentid++;
                    try (FileWriter fw = new FileWriter("comments.txt", true);
                         BufferedWriter bw = new BufferedWriter(fw);
                         PrintWriter out = new PrintWriter(bw)) {
                        out.println(comment.getId() + "," + comment.getUsername() + "," + comment.getText() + "," + id[1] + "," + comment.getDate());
                    } catch (IOException e) {
                    }
                    System.out.println("{'status' : 'ok' , 'message' : 'Comment added successfully'}");
                }
            }
        }

        if(strings[0].equals("-delete-comment-by-id")) {
            int ok = 0;
            int ok2 = 0;
            if(strings.length <= 2)
                System.out.println("{ 'status' : 'error', 'message' : 'You need to be authenticated'}");
            else {
                String[] username = strings[1].split("'");
                String[] password = strings[2].split("'");
                try (BufferedReader br = new BufferedReader(new FileReader("users.txt"))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        String[] parts = line.split(",");
                        if(parts[0].equals(username[1])) {
                            if(parts[1].equals(password[1]))
                                ok = 1;
                        }
                    }
                } catch (IOException e) {
                }
                if(ok == 0){
                    System.out.println("{ 'status' : 'error', 'message' : 'Login failed'}");
                    return;
                }
            }
            if(ok == 1) {
                if(strings.length < 4)
                    System.out.println("{ 'status' : 'error', 'message' : 'No identifier was provided'}");
                else{
                    String[] username = strings[1].split("'");
                    String[] id = strings[3].split("'");
                    ArrayList<String> vector = new ArrayList<String>();
                    try (BufferedReader br = new BufferedReader(new FileReader("comments.txt"))) {
                        String line;
                        while ((line = br.readLine()) != null) {
                            String[] parts = line.split(",");
                            if(parts[0].equals(id[1]) && parts[1].equals(username[1])) {
                                ok2 = 1;
                                continue;
                            }
                            vector.add(line);
                        }
                    } catch (IOException e) {
                    }
                    if(ok2 == 0){
                        System.out.println("{ 'status' : 'error', 'message' : 'The identifier was not valid'}");
                        return;
                    } else {
                        try (FileWriter fw = new FileWriter("comments.txt", false);
                             BufferedWriter bw = new BufferedWriter(fw);
                             PrintWriter out = new PrintWriter(bw)) {
                            out.println("");
                        } catch (IOException e) {
                        }

                        for (int i = 0; i < vector.size(); i++) {
                            try (FileWriter fw = new FileWriter("comments.txt", true);
                                 BufferedWriter bw = new BufferedWriter(fw);
                                 PrintWriter out = new PrintWriter(bw)) {
                                out.println(vector.get(i));
                            } catch (IOException e) {
                            }
                        }

                        System.out.println("{'status':'ok','message':'Operation executed successfully'}");
                    }
                }
            }
        }

        if (strings[0].equals("-like-comment")) {
            int ok = 0;
            if(strings.length <= 2)
                System.out.println("{ 'status' : 'error', 'message' : 'You need to be authenticated'}");
            else {
                String[] username = strings[1].split("'");
                String[] password = strings[2].split("'");
                try (BufferedReader br = new BufferedReader(new FileReader("users.txt"))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        String[] parts = line.split(",");
                        if(parts[0].equals(username[1])) {
                            if(parts[1].equals(password[1]))
                                ok = 1;
                        }
                    }
                } catch (IOException e) {
                }
                if(ok == 0){
                    System.out.println("{ 'status' : 'error', 'message' : 'Login failed'}");
                    return;
                }
            }
            if(ok == 1){
                if(strings.length <= 3)
                    System.out.println("{ 'status' : 'error', 'message' : 'No comment identifier to like was provided'}");
                else {
                    String[] id = strings[3].split("'");
                    String[] username = strings[1].split("'");
                    Comment comment = new Comment("", "", 0, "");
                    comment.like(username, id);
                }
            }
        }

        if(strings[0].equals("-unlike-comment")) {
            int ok = 0;
            if(strings.length <= 2)
                System.out.println("{ 'status' : 'error', 'message' : 'You need to be authenticated'}");
            else {
                String[] username = strings[1].split("'");
                String[] password = strings[2].split("'");
                try (BufferedReader br = new BufferedReader(new FileReader("users.txt"))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        String[] parts = line.split(",");
                        if(parts[0].equals(username[1])) {
                            if(parts[1].equals(password[1]))
                                ok = 1;
                        }
                    }
                } catch (IOException e) {
                }
                if(ok == 0){
                    System.out.println("{ 'status' : 'error', 'message' : 'Login failed'}");
                    return;
                }
            }
            if(ok == 1){
                if(strings.length <= 3)
                    System.out.println("{ 'status' : 'error', 'message' : 'No comment identifier to unlike was provided'}");
                else {
                    String[] id = strings[3].split("'");
                    String[] username = strings[1].split("'");
                    Comment comment = new Comment("", "", 0, "");
                    comment.unlike(username, id);
                }
            }
        }

        if (strings[0].equals("-get-followings-posts")) {
            int ok = 0;
            if(strings.length <= 2)
                System.out.println("{ 'status' : 'error', 'message' : 'You need to be authenticated'}");
            else {
                String[] username = strings[1].split("'");
                String[] password = strings[2].split("'");
                try (BufferedReader br = new BufferedReader(new FileReader("users.txt"))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        String[] parts = line.split(",");
                        if(parts[0].equals(username[1])) {
                            if(parts[1].equals(password[1]))
                                ok = 1;
                        }
                    }
                } catch (IOException e) {
                }
                if(ok == 0){
                    System.out.println("{ 'status' : 'error', 'message' : 'Login failed'}");
                    return;
                }
            }
            if (ok == 1) {
                System.out.print("{ 'status' : 'ok', 'message' : [");
                String[] username = strings[1].split("'");
                ArrayList<String> output = new ArrayList<>();
                try (BufferedReader br = new BufferedReader(new FileReader("followers.txt"))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        String[] parts = line.split(",");
                        if(parts[0].equals(username[1])) {
                            try (BufferedReader br2 = new BufferedReader(new FileReader("posts.txt"))) {
                                String line2;
                                while ((line2 = br2.readLine()) != null) {
                                    String[] parts2 = line2.split(",");
                                    if(parts2.length > 2 && parts2[1].equals(parts[1])) {
                                        output.add("{'post_id':'" + parts2[0] + "','post_text':'" + parts2[2] + "','post_date':'" + parts2[3] + "','username':'" + parts2[1] + "'}");
                                    }
                                }
                            } catch (IOException e) {
                            }
                        }
                    }
                } catch (IOException e) {
                }
                for (int i = output.size() - 1; i >= 0; i--) {
                    if (i != output.size() - 1)
                        System.out.print(",");
                    System.out.print(output.get(i));
                }
                System.out.println("]}");
            }
        }

        if (strings[0].equals("-get-user-posts")) {
            int ok = 0;
            int ok2 = 0;
            if(strings.length <= 2)
                System.out.println("{ 'status' : 'error', 'message' : 'You need to be authenticated'}");
            else {
                String[] username = strings[1].split("'");
                String[] password = strings[2].split("'");
                try (BufferedReader br = new BufferedReader(new FileReader("users.txt"))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        String[] parts = line.split(",");
                        if(parts[0].equals(username[1])) {
                            if(parts[1].equals(password[1]))
                                ok = 1;
                        }
                    }
                } catch (IOException e) {
                }
                if(ok == 0){
                    System.out.println("{ 'status' : 'error', 'message' : 'Login failed'}");
                    return;
                }
            }
            if (ok == 1) {
                if (strings.length <= 3)
                    System.out.println("{ 'status' : 'error', 'message' : 'No username to list posts was provided'}");
                else {
                    String[] username = strings[1].split("'");
                    String[] usernameFollowed = strings[3].split("'");
                    try (BufferedReader br = new BufferedReader(new FileReader("followers.txt"))) {
                        String line;
                        while ((line = br.readLine()) != null) {
                            String[] parts = line.split(",");
                            if(parts[0].equals(username[1]) && parts[1].equals(usernameFollowed[1])) {
                                ok2 = 1;
                            }
                        }
                    } catch (IOException e) {
                    }

                    if (ok2 == 0){
                        System.out.println("{ 'status' : 'error', 'message' : 'The username to list posts was not valid'}");
                    } else {
                        System.out.print("{ 'status' : 'ok', 'message' : [");
                        ArrayList<String> output = new ArrayList<>();
                        try (BufferedReader br = new BufferedReader(new FileReader("posts.txt"))) {
                            String line;
                            while ((line = br.readLine()) != null) {
                                String[] parts = line.split(",");
                                if (parts.length > 1 && parts[1].equals(usernameFollowed[1])) {
                                    output.add("{'post_id':'" + parts[0] + "','post_text':'" + parts[2] + "','post_date':'" + parts[3] + "'}");
                                }
                            }
                        } catch (IOException e) {
                        }
                        for (int i = output.size() - 1; i >= 0; i--) {
                            if (i != output.size() - 1)
                                System.out.print(",");
                            System.out.print(output.get(i));
                        }
                        System.out.println("]}");
                    }
                }
            }
        }

        if (strings[0].equals("-get-post-details")) {
            int ok = 0;
            int ok2 = 0;
            if(strings.length <= 2)
                System.out.println("{ 'status' : 'error', 'message' : 'You need to be authenticated'}");
            else {
                String[] username = strings[1].split("'");
                String[] password = strings[2].split("'");
                try (BufferedReader br = new BufferedReader(new FileReader("users.txt"))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        String[] parts = line.split(",");
                        if(parts[0].equals(username[1])) {
                            if(parts[1].equals(password[1]))
                                ok = 1;
                        }
                    }
                } catch (IOException e) {
                }
                if(ok == 0){
                    System.out.println("{ 'status' : 'error', 'message' : 'Login failed'}");
                    return;
                }
            }
            if (ok == 1){
                if (strings.length <= 3) {
                    System.out.println("{ 'status' : 'error', 'message' : 'No post identifier was provided'}");
                } else {
                    int numberlikes = 0;
                    String[] id = strings[3].split("'");
                    String[] username = strings[1].split("'");
                    try (BufferedReader br = new BufferedReader(new FileReader("posts.txt"))) {
                        String line;
                        while ((line = br.readLine()) != null) {
                            String[] parts = line.split(",");
                            if (parts[0].equals(id[1])) {
                                ok2 = 1;
                                System.out.print("{'status':'ok','message': [{ 'post_text' : '" + parts[2] + "', 'post_date' : '" + parts[3] + "', 'username' : '" + parts[1] + "','number_of_likes':'");
                            }
                        }
                    } catch (IOException e) {
                    }
                    if (ok2 == 1) {
                    try (BufferedReader br = new BufferedReader(new FileReader("likepost.txt"))) {
                        String line;
                        while ((line = br.readLine()) != null) {
                            String[] parts = line.split(",");
                            if (parts.length > 1 && parts[1].equals(id[1])) {
                                numberlikes++;
                            }
                        }
                    } catch (IOException e) {
                    }
                    System.out.print(numberlikes + "', 'comments' : [");
                    int virgula = 0;
                    try (BufferedReader br = new BufferedReader(new FileReader("comments.txt"))) {
                        String line;
                        while ((line = br.readLine()) != null) {
                            String[] parts = line.split(",");
                            if (parts.length > 2 && parts[3].equals(id[1])) {
                                int numberlikes2 = 0;
                                try (BufferedReader br2 = new BufferedReader(new FileReader("likecomment.txt"))) {
                                    String line2;
                                    while ((line2 = br.readLine()) != null) {
                                        String[] parts2 = line2.split(",");
                                        if (parts2.length > 1 && parts2[1].equals(id[1])) {
                                            numberlikes2++;
                                        }
                                    }
                                } catch (IOException e) {
                                }
                                if (virgula == 1)
                                    System.out.print(",");
                                System.out.print("{ 'comment_id' : '" + parts[0] + "', 'comment_text' : '" + parts[2] + "','comment_date' : '" + parts[4] + "', 'username' : '" + parts[1] + "','number_of_likes':'" + numberlikes2 + "'}");
                                virgula = 1;
                            }
                        }
                        System.out.print("] }] }");
                    } catch (IOException e) {
                    }
                    } else {
                        System.out.println("{ 'status' : 'error', 'message' : 'The post identifier was not valid'}");
                    }

                }
            }
        }

        if (strings[0].equals("-get-following")) {
            int ok = 0;
            if(strings.length <= 2)
                System.out.println("{ 'status' : 'error', 'message' : 'You need to be authenticated'}");
            else {
                String[] username = strings[1].split("'");
                String[] password = strings[2].split("'");
                try (BufferedReader br = new BufferedReader(new FileReader("users.txt"))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        String[] parts = line.split(",");
                        if(parts[0].equals(username[1])) {
                            if(parts[1].equals(password[1]))
                                ok = 1;
                        }
                    }
                } catch (IOException e) {
                }
                if(ok == 0){
                    System.out.println("{ 'status' : 'error', 'message' : 'Login failed'}");
                    return;
                }
            }

            if (ok == 1){
                String[] username = strings[1].split("'");
                System.out.print("{ 'status' : 'ok', 'message' : [");
                int virgula = 0;
                try (BufferedReader br = new BufferedReader(new FileReader("followers.txt"))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        String[] parts = line.split(",");
                        if (parts[0].equals(username[1])) {
                            if (virgula == 1)
                                System.out.print(",");
                            System.out.print("'" + parts[1] + "'");
                            virgula = 1;
                        }
                    }
                } catch (IOException e) {
                }
                System.out.print("]}");
            }
        }

        if (strings[0].equals("-get-followers")) {
            int ok = 0;
            if(strings.length <= 2)
                System.out.println("{ 'status' : 'error', 'message' : 'You need to be authenticated'}");
            else {
                String[] username = strings[1].split("'");
                String[] password = strings[2].split("'");
                try (BufferedReader br = new BufferedReader(new FileReader("users.txt"))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        String[] parts = line.split(",");
                        if(parts[0].equals(username[1])) {
                            if(parts[1].equals(password[1]))
                                ok = 1;
                        }
                    }
                } catch (IOException e) {
                }
                if(ok == 0){
                    System.out.println("{ 'status' : 'error', 'message' : 'Login failed'}");
                    return;
                }
            }

            if (ok == 1) {
                if (strings.length <= 3){
                    System.out.println("{ 'status' : 'error', 'message' : 'No username to list followers was provided'}");
                } else {
                    String[] username = strings[1].split("'");
                    String[] usernameFollowed = strings[3].split("'");
                    int ok2 = 0;
                    try (BufferedReader br = new BufferedReader(new FileReader("users.txt"))) {
                        String line;
                        while ((line = br.readLine()) != null) {
                            String[] parts = line.split(",");
                            if (parts[0].equals(usernameFollowed[1])) {
                                ok2 = 1;
                            }
                        }
                    } catch (IOException e) {
                    }

                    if (ok2 == 0){
                        System.out.println("{ 'status' : 'error', 'message' : 'The username to list followers was not valid'}");
                    } else {
                        System.out.print("{ 'status' : 'ok', 'message' : [");
                        int virgula = 0;
                        try (BufferedReader br = new BufferedReader(new FileReader("followers.txt"))) {
                            String line;
                            while ((line = br.readLine()) != null) {
                                String[] parts = line.split(",");
                                if (parts.length > 1 && parts[1].equals(usernameFollowed[1])) {
                                    if (virgula == 1)
                                        System.out.print(",");
                                    System.out.print("'" + parts[0] + "'");
                                    virgula = 1;
                                }
                            }
                        } catch (IOException e) {
                        }
                        System.out.print("]}");
                    }
                }
            }
        }

        if (strings[0].equals("-get-most-liked-posts")) {
            int ok = 0;
            if(strings.length <= 2)
                System.out.println("{ 'status' : 'error', 'message' : 'You need to be authenticated'}");
            else {
                String[] username = strings[1].split("'");
                String[] password = strings[2].split("'");
                try (BufferedReader br = new BufferedReader(new FileReader("users.txt"))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        String[] parts = line.split(",");
                        if(parts[0].equals(username[1])) {
                            if(parts[1].equals(password[1]))
                                ok = 1;
                        }
                    }
                } catch (IOException e) {
                }
                if(ok == 0){
                    System.out.println("{ 'status' : 'error', 'message' : 'Login failed'}");
                    return;
                }
            }
            if (ok == 1){
                System.out.print("{ 'status' : 'ok', 'message' : [");
                ArrayList<String> vectorlikes = new ArrayList<>();
                try (BufferedReader br = new BufferedReader(new FileReader("posts.txt"))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        String[] parts = line.split(",");
                        int numberlikes = 0;
                        try (BufferedReader br2 = new BufferedReader(new FileReader("likepost.txt"))) {
                            String line2;
                            while ((line2 = br2.readLine()) != null) {
                                String[] parts2 = line2.split(",");
                                if (parts2.length > 1 && parts2[1].equals(parts[0])) {
                                    numberlikes++;
                                }
                            }
                        } catch (IOException e) {
                        }
                        if (parts.length > 1)
                            vectorlikes.add(numberlikes + "," + parts[0] + "," + parts[1] + "," + parts[2] + "," + parts[3]);
                    }
                } catch (IOException e) {
                }

                int virgula = 0;
                for (int i = 0; i < 5; i++) {
                    int max = 0, mostliked = 0;
                    for (int j = 0; j < vectorlikes.size(); j++) {
                        String[] parts = vectorlikes.get(j).split(",");
                        int nrlikes = Integer.parseInt(parts[0]);
                        if (nrlikes > max) {
                            max = nrlikes;
                            mostliked = j;
                        }
                    }
                    if (virgula == 1 && i < 3)
                        System.out.print(",");
                    if (vectorlikes.size() > 0) {
                        String[] parts2= vectorlikes.get(mostliked).split(",");
                        System.out.print("{'post_id':'" + parts2[1] + "','post_text':'" + parts2[3] + "','post_date':'" + parts2[4] + "','username':'" + parts2[2] + "','number_of_likes':'" + parts2[0] + "'}");
                        vectorlikes.remove(mostliked);
                    }
                    virgula = 1;
                }
                System.out.println(" ]}");
            }
        }

        if (strings[0].equals("-get-most-commented-posts")) {
            int ok = 0;
            if (strings.length <= 2)
                System.out.println("{ 'status' : 'error', 'message' : 'You need to be authenticated'}");
            else {
                String[] username = strings[1].split("'");
                String[] password = strings[2].split("'");
                try (BufferedReader br = new BufferedReader(new FileReader("users.txt"))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        String[] parts = line.split(",");
                        if (parts[0].equals(username[1])) {
                            if (parts[1].equals(password[1]))
                                ok = 1;
                        }
                    }
                } catch (IOException e) {
                }
                if (ok == 0) {
                    System.out.println("{ 'status' : 'error', 'message' : 'Login failed'}");
                    return;
                }
            }
            if (ok == 1) {
                System.out.print("{ 'status' : 'ok', 'message' : [");
                ArrayList<String> vectorcomments = new ArrayList<>();
                try (BufferedReader br = new BufferedReader(new FileReader("posts.txt"))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        String[] parts = line.split(",");
                        int numbercomments = 0;
                        try (BufferedReader br2 = new BufferedReader(new FileReader("comments.txt"))) {
                            String line2;
                            while ((line2 = br2.readLine()) != null) {
                                String[] parts2 = line2.split(",");
                                if (parts2.length > 2 && parts2[3].equals(parts[0])) {
                                    numbercomments++;
                                }
                            }
                        } catch (IOException e) {
                        }
                        if (parts.length > 1)
                            vectorcomments.add(numbercomments + "," + parts[0] + "," + parts[1] + "," + parts[2] + "," + parts[3]);
                    }
                } catch (IOException e) {
                }

                int virgula = 0;
                for (int i = 0; i < 5; i++) {
                    int max = 0, mostcommented = 0;
                    for (int j = 0; j < vectorcomments.size(); j++) {
                        String[] parts = vectorcomments.get(j).split(",");
                        int nrcomments = Integer.parseInt(parts[0]);
                        if (nrcomments > max) {
                            max = nrcomments;
                            mostcommented = j;
                        }
                    }
                    if (virgula == 1 && i < 3)
                        System.out.print(",");
                    if (vectorcomments.size() > 0) {
                        String[] parts2 = vectorcomments.get(mostcommented).split(",");
                        System.out.print("{'post_id':'" + parts2[1] + "','post_text':'" + parts2[3] + "','post_date':'" + parts2[4] + "','username':'" + parts2[2] + "','number_of_comments':'" + parts2[0] + "'}");
                        vectorcomments.remove(mostcommented);
                    }
                    virgula = 1;
                }
                System.out.println("]}");
            }
        }

        if (strings[0].equals("-get-most-followed-users")) {
            int ok = 0;
            if (strings.length <= 2)
                System.out.println("{ 'status' : 'error', 'message' : 'You need to be authenticated'}");
            else {
                String[] username = strings[1].split("'");
                String[] password = strings[2].split("'");
                try (BufferedReader br = new BufferedReader(new FileReader("users.txt"))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        String[] parts = line.split(",");
                        if (parts[0].equals(username[1])) {
                            if (parts[1].equals(password[1]))
                                ok = 1;
                        }
                    }
                } catch (IOException e) {
                }
                if (ok == 0) {
                    System.out.println("{ 'status' : 'error', 'message' : 'Login failed'}");
                    return;
                }
            }
            if (ok == 1) {
                System.out.print("{ 'status' : 'ok', 'message' : [");
                ArrayList<String> vectorfollowers = new ArrayList<>();
                try (BufferedReader br = new BufferedReader(new FileReader("users.txt"))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        String[] parts = line.split(",");
                        int numberfollowers = 0;
                        try (BufferedReader br2 = new BufferedReader(new FileReader("followers.txt"))) {
                            String line2;
                            while ((line2 = br2.readLine()) != null) {
                                String[] parts2 = line2.split(",");
                                if (parts2.length > 1 && parts2[1].equals(parts[0])) {
                                    numberfollowers++;
                                }
                            }
                        } catch (IOException e) {
                        }
                        if (parts.length > 1)
                            vectorfollowers.add(numberfollowers + "," + parts[0]);
                    }
                } catch (IOException e) {
                }

                int virgula = 0;
                for (int i = 0; i < 5; i++) {
                    int max = 0, mostfollowed = 0;
                    for (int j = 0; j < vectorfollowers.size(); j++) {
                        String[] parts = vectorfollowers.get(j).split(",");
                        int nrfollowers = Integer.parseInt(parts[0]);
                        if (nrfollowers > max) {
                            max = nrfollowers;
                            mostfollowed = j;
                        }
                    }
                    if (virgula == 1 && i < 5)
                        System.out.print(",");
                    if (vectorfollowers.size() > 0) {
                        String[] parts2 = vectorfollowers.get(mostfollowed).split(",");
                        System.out.print("{'username':'" + parts2[1] + "','number_of_followers':'" + parts2[0] + "'}");
                        vectorfollowers.remove(mostfollowed);
                    }
                    virgula = 1;
                }
                System.out.println(" ]}");
            }
        }

        if (strings[0].equals("-get-most-liked-users")) {
            int ok = 0;
            if (strings.length <= 2)
                System.out.println("{ 'status' : 'error', 'message' : 'You need to be authenticated'}");
            else {
                String[] username = strings[1].split("'");
                String[] password = strings[2].split("'");
                try (BufferedReader br = new BufferedReader(new FileReader("users.txt"))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        String[] parts = line.split(",");
                        if (parts[0].equals(username[1])) {
                            if (parts[1].equals(password[1]))
                                ok = 1;
                        }
                    }
                } catch (IOException e) {
                }
                if (ok == 0) {
                    System.out.println("{ 'status' : 'error', 'message' : 'Login failed'}");
                    return;
                }
            }
            if (ok == 1) {
                System.out.print("{ 'status' : 'ok', 'message' : [");
                ArrayList<String> vectorlikes = new ArrayList<>();
                try (BufferedReader br = new BufferedReader(new FileReader("posts.txt"))) {
                    String line;
                    while ((line = br.readLine()) != null) {
                        String[] parts = line.split(",");
                        int numberlikes = 0;
                        try (BufferedReader br2 = new BufferedReader(new FileReader("likepost.txt"))) {
                            String line2;
                            while ((line2 = br2.readLine()) != null) {
                                String[] parts2 = line2.split(",");
                                if (parts2.length > 1 && parts2[1].equals(parts[0])) {
                                    numberlikes++;
                                }
                            }
                        } catch (IOException e) {
                        }
                        try (BufferedReader br3 = new BufferedReader(new FileReader("likecomment.txt"))) {
                            String line3;
                            while ((line3 = br3.readLine()) != null) {
                                String[] parts3 = line3.split(",");
                                if (parts3.length > 1 && parts3[1].equals(parts[0])) {
                                    numberlikes++;
                                }
                            }
                        } catch (IOException e) {
                        }
                        if (parts.length > 1)
                            vectorlikes.add(numberlikes + "," + parts[1]);
                    }
                } catch (IOException e) {
                }

                int virgula = 0;
                for (int i = 0; i < 5; i++) {
                    int max = 0, mostliked = 0;
                    for (int j = 0; j < vectorlikes.size(); j++) {
                        String[] parts = vectorlikes.get(j).split(",");
                        int nrlikes = Integer.parseInt(parts[0]);
                        if (nrlikes > max) {
                            max = nrlikes;
                            mostliked = j;
                        }
                    }
                    if (virgula == 1 && i < 5)
                        System.out.print(",");
                    if (vectorlikes.size() > 0) {
                        String[] parts2 = vectorlikes.get(mostliked).split(",");
                        System.out.print("{'username':'" + parts2[1] + "','number_of_likes':'" + parts2[0] + "'}");
                        vectorlikes.remove(mostliked);
                    }
                    virgula = 1;
                }
                System.out.println("]}");
            }
        }

        if (strings[0].equals("-cleanup-all")) {
            postid = 1;
            commentid = 1;
            try (FileWriter fw = new FileWriter("users.txt", false);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter out = new PrintWriter(bw)) {
                out.println("");
            } catch (IOException e) {
            }
            try (FileWriter fw = new FileWriter("posts.txt", false);
                 BufferedWriter bw = new BufferedWriter(fw);
                 PrintWriter out = new PrintWriter(bw)) {
                out.println("");
            } catch (IOException e) {
            }
            try (FileWriter fw = new FileWriter("followers.txt", false);
                 BufferedWriter bw = new BufferedWriter(fw);
                 PrintWriter out = new PrintWriter(bw)) {
                out.println("");
            } catch (IOException e) {
            }
            try (FileWriter fw = new FileWriter("likepost.txt", false);
                 BufferedWriter bw = new BufferedWriter(fw);
                 PrintWriter out = new PrintWriter(bw)) {
                out.println("");
            } catch (IOException e) {
            }
            try (FileWriter fw = new FileWriter("comments.txt", false);
                 BufferedWriter bw = new BufferedWriter(fw);
                 PrintWriter out = new PrintWriter(bw)) {
                out.println("");
            } catch (IOException e) {
            }
            try (FileWriter fw = new FileWriter("likecomment.txt", false);
                 BufferedWriter bw = new BufferedWriter(fw);
                 PrintWriter out = new PrintWriter(bw)) {
                out.println("");
            } catch (IOException e) {
            }
            System.out.println("{'status':'ok','message':'Cleanup finished successfully'}");
        }
    }
}